apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: devx-helloworld-springboot-test-eim5b
    backstage.io/kubernetes-id: devx-helloworld-springboot-test-eim5b
  name: devx-helloworld-springboot-test-eim5b
  namespace: '{{ .Values.config.namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devx-helloworld-springboot-test-eim5b
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devx-helloworld-springboot-test-eim5b
        backstage.io/kubernetes-id: devx-helloworld-springboot-test-eim5b
    spec:
      containers:
      - image: '{{ .Values.config.image.name }}':'{{ .Values.config.image.tag }}'
        imagePullPolicy: IfNotPresent
        name: devx-helloworld-springboot-test-eim5b
        resources: {}
        ports:
          - containerPort: 8080 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 5
status: {}
